mutation SignUp($email: String!, $password: String!, $displayName: String!) {
  createUser(email: $email, password: $password, displayName: $displayName) {
    user {
      id
      displayName
      email
      createdAt
      updatedAt
      deletedAt
      externalId
      team {
        id
        name
        code
        sport
        creator {
          id
          displayName
          email
          externalId
        }
      }
    }
    refreshToken
    accessToken
  }
}

mutation SignIn($email: String!, $password: String!) {
  signIn(email: $email, password: $password) {
    user {
      id
      displayName
      createdAt
      updatedAt
      deletedAt
      externalId
      email
      team {
        id
        name
        code
        sport
        creator {
          id
          displayName
          externalId
          email
        }
      }
    }
    refreshToken
    accessToken
  }
}

mutation RefreshToken($input: RefreshTokenInput!) {
  refreshToken(input: $input) {
    accessToken
    refreshToken
    expiredAt
  }
}

mutation CreateTeam($name: String!, $sport: String) {
  createTeam(name: $name, sport: $sport) {
    id
    name
    code
    creator {
      id
      displayName
      email
      createdAt
      updatedAt
      deletedAt
      externalId
    }
    createdAt
    updatedAt
    sport
  }
}

mutation JoinTeam($code: String!) {
  joinTeam(code: $code) {
    id
    name
    code
    sport
    creator {
      id
      displayName
      email
      createdAt
      updatedAt
      deletedAt
      externalId
    }
    createdAt
    updatedAt
  }
}

mutation CreateMatch($name: String!, $date: DateTime!, $type: MatchType!) {
  createMatch(name: $name, date: $date, type: $type) {
    id
    name
    date
    type
    creator {
      displayName
      email
    }
    team {
      name
      code
    }
    createdAt
    updatedAt
    deletedAt
    players {
      displayName
      email
    }
    votingSession {
      status
      timeRemaining
      voteResult {
        flop {
          id
          displayName
        }
        top {
          id
          displayName
        }
      }
    }
  }
}
