mutation SignUp(
  $email: String!
  $password: String!
  $displayName: String!
  $nickname: String
) {
  createUser(
    email: $email
    password: $password
    displayName: $displayName
    nickname: $nickname
  ) {
    user {
      id
      displayName
      nickname
      avatarUrl
      email
      createdAt
      team {
        id
        name
        code
        sport
        crestUrl
        creator {
          id
          displayName
          nickname
        }
      }
    }
    refreshToken
    accessToken
  }
}

mutation SignIn($email: String!, $password: String!) {
  signIn(email: $email, password: $password) {
    user {
      id
      displayName
      nickname
      avatarUrl
      createdAt
      email
      team {
        id
        name
        code
        sport
        crestUrl
        creator {
          id
          displayName
          nickname
        }
      }
    }
    refreshToken
    accessToken
  }
}

mutation RefreshToken($input: RefreshTokenInput!) {
  refreshToken(input: $input) {
    accessToken
    refreshToken
    expiredAt
  }
}

mutation CreateTeam($name: String!, $sport: String) {
  createTeam(name: $name, sport: $sport) {
    id
    name
    code
    crestUrl
    creator {
      id
      displayName
      nickname
    }
    createdAt
    sport
  }
}

mutation JoinTeam($code: String!) {
  joinTeam(code: $code) {
    id
    name
    code
    sport
    crestUrl
    creator {
      id
      displayName
      nickname
    }
    createdAt
  }
}

mutation CreateMatch($name: String!, $date: DateTime!, $type: MatchType!) {
  createMatch(name: $name, date: $date, type: $type) {
    id
    name
    date
    type
    creator {
      id
      displayName
      nickname
      avatarUrl
    }
    team {
      id
      name
      code
    }
    createdAt
    players {
      id
      displayName
      nickname
      avatarUrl
    }
    votingSession {
      id
      status
      timeRemaining
      voteResult {
        flop {
          id
          displayName
        }
        top {
          id
          displayName
        }
      }
    }
  }
}
